### ISSUE TITLE
speed of read_contents() on accordion tree

### ISSUE THREAD

**Issue by akrzos** [RedHatQE/cfme_tests#1204]
Testing against some environments at scale, reading the tree takes a long time.  In one instance an accordion with ~5k VMs takes almost an hour to read the tree using chrome as the browser.  This comes very close to the session timeout and could fail the test just from a tree that is too large.  This issue will become bigger as typical test environments and databases grow.

**Comment by mfalesni** [comment]
I think I could move the logic in a JS script that would be much faster.

**Comment by mfalesni** [comment]
Resolved.
