### ISSUE TITLE
[PRT] - Clean up running docker instances on set_invalid_runs

### ISSUE THREAD

**Issue by psav** [RedHatQE/cfme_tests#1396]
Would be nice to initiate a "killing" of docker instances if they are no longer valid. Only disadvantage is the possibility of leaving behind stray appliances because of upgrade/multi appliance tests. We could have a metadata flag to request that tests not be killed. Even better, we could have something to gracefully kill the tests inside the docker container.

**Comment by mfalesni** [comment]
@psav http://stackoverflow.com/a/25690544
