### ISSUE TITLE
NoSuchElementException when server_roles = None

### ISSUE THREAD

**Issue by akrzos** [RedHatQE/cfme_tests#1642]
Attempting to limit an appliance's roles using server_roles = None to turn off everything except the UI role results in an error.
 
` [E] NoSuchElementException: Message: Element input#server_roles_storage_metrics_processor not found on page. (fixtures/log.py:61)`

Furthermore it does it the old fashion way rather than validating via the database.  You can still accomplish limited a fresh appliance to the UI role via:

`server_roles="-database_operations -event -ems_inventory -ems_operations -reporting  -scheduler -smartstate -web_services"`

**Comment by mfalesni** [comment]
That is because the storage options are not there unless the storage option is enabled. I'll look in it.

**Comment by akrzos** [comment]
Yeah I figured it was because that feature is not enabled on the appliance I was testing against.  Also --smartstate should be --smartproxy now.  Consequently you can just have both listed if that turns out to be a version specific string.
