### ISSUE TITLE
Sprout should utilize shepherd appliances whilst waiting for a provision

### ISSUE THREAD

**Issue by psav** [RedHatQE/cfme_tests#1856]
Scenario is a little complex, but does add a lot of time to large pool fulfillment. Some providers are much quicker at provisioning than others. Imagine a large pool request comes in and sprout doesn't have the capacity to fulfill it. Currently it appears that sprout starts off a provision and adds it to the pool. Sometimes however, another provider also starts a provision and there is a situation where a job is held up for 10-20 minutes even though there is a free appliance in shepherd. Is it possible for sprout to use this free appliance and keep the other one to go in the pool when it's finished?

**Comment by mfalesni** [comment]
I think I can poke that. Maybe not right now but it should not be too difficult.

**Comment by mfalesni** [comment]
#1979 solved this.
