### ISSUE TITLE
update_template.sh returns "VM template name must not exceed 40 characters"

### ISSUE THREAD

**Issue by thom-at-redhat** [RedHatQE/cfme_tests#2106]
Traced to utils/mgmt_system/rhevm.py if original VM name is > 40 characters.  Possible resolutions:
1) Add an option for new template name
2) Mangle original VM name to be <= 40 characters (RHEV limit)

**Comment by jkrocil** [comment]
@mfalesni @amavinag is this issue still valid?

**Comment by mfalesni** [comment]
I guess not since you can always make the name shorter than 40 characters.
