### ISSUE TITLE
Provider locator cleanup

### ISSUE THREAD

**Issue by seandst** [RedHatQE/cfme_tests#796]
This is a little bit of low-hanging fruit to be picked.

Here's a comment:
https://github.com/RedHatQE/cfme_tests/pull/767#issuecomment-44576850

And here's the details region:
https://github.com/RedHatQE/cfme_tests/blob/master/cfme/infrastructure/provider.py#L33

It just needs to have an identifying_loc to do what's needed in the comment, and that locator is already defined inside the Provider._on_details_page method.`

**Comment by mfalesni** [comment]
@seandst I believe we did a lot on providers so this issue can be closed.
